---
- name: install apache package
  apt:
    pkg: apache2
  register: result
  until: result|succeeded
  retries: 5

- name: install www-browser
  apt:
    pkg: lynx-cur
  register: result
  until: result|succeeded
  retries: 5

- name: install apache module packages
  apt:
    pkg: "{{ item }}"
  register: result
  until: result|succeeded
  retries: 5
  with_items: "{{ apache.modules }}"

- name: enable apache modules
  apache2_module:
    name: "{{ item }}"
  with_items:
    - headers
    - ssl
    - rewrite
    - status
    - proxy_http
  notify: reload apache

- name: install passlib pip module
  pip:
    name: passlib
  register: result
  until: result|succeeded
  retries: 5

- name: disable default vhost
  file:
    dest: "/etc/apache2/sites-enabled/{{ item }}"
    state: absent
  with_items:
    - 000-default
    - 000-default.conf
    - default
    - default.conf
  notify: stop apache

- name: extra configuration from template
  template:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-available/"
  with_fileglob: ../templates/etc/apache2/*

- name: extra configuration from file
  copy:
    src: "{{ item }}"
    dest: "/etc/apache2/conf-available/"
  with_fileglob: ../files/etc/apache2/*

- name: enable extra configuration
  file:
    src: /etc/apache2/conf-available/{{ item }}
    dest: /etc/apache2/conf-enabled/{{ item }}
    state: link
  with_items:
    - logs.conf
    - ports.conf
  notify: reload apache

- name: install apache healthcheck file
  template:
    src: var/www/html/health_check
    dest: /var/www/html/health_check
  when: apache.health_check_enabled|default('False')|bool

- meta: flush_handlers

- name: ensure apache is running
  service:
    name: apache2
    state: started
    enabled: yes
  when: apache.listen|length > 0

- name: ensure apache is stopped
  service:
    name: apache2
    state: stopped
    enabled: no
  when: apache.listen|length == 0

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
