---
- name: create netdata user
  user: name=netdata comment=netdata shell=/bin/false
        system=yes home=/nonexistent

- name: netdata defaults
  lineinfile:
    dest: /etc/default/netdata
    line: "{{ item }}"
    create: true
    mode: 0644
  with_items:
    - 'PIDFILE="/var/run/netdata.pid"'
    - 'EXTRA_OPTS="-P /var/run/netdata.pid"'

- include: ./roles/_cuttle/tasks/install_deb.yml
  vars:
    package_name: netdata
    package_url: "{{ netdata.package }}"

- name: ensure netdata service is running
  service:
    name: netdata
    enabled: true
    state: started

- name: allow access to netdata web
  ufw: rule=allow to_port=19999 proto=tcp src={{ item }}
  with_items: "{{ netdata.firewall.allow_from }}"
  tags:
    - firewall

- name: configure netdata
  template:
    src: etc/netdata/netdata.conf
    dest: /etc/netdata/netdata.conf
  tags: netdata-config
  notify: restart netdata

- name: set up log rotation for netdata
  logrotate:
    name: netdata
    path: /var/log/netdata/*.log
  args:
    options:
      - "{{ netdata.logrotate.frequency }}"
      - "size {{ netdata.logrotate.size }}"
      - "rotate {{ netdata.logrotate.rotations }}"
      - missingok
      - copytruncate
      - compress
      - notifempty

- meta: flush_handlers

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
