---
- name: enable apache mod ssl
  apache2_module: name=ssl
  notify: restart apache
  when: apache_auth.ssl.enabled

#- name: install ssl key
#  template: src=auth_basic/etc/ssl/private/apache_auth.key
#            dest=/etc/ssl/private/{{ apache_auth.vhost_name }}.key
#            owner=root group=ssl-key mode=0640
#  when: apache_auth.ssl.enabled
#  notify: restart apache

#- name: install ssl cert
#  template: src=auth_basic/etc/ssl/certs/apache_auth.pem
#            dest=/etc/ssl/certs/{{ apache_auth.vhost_name }}.pem
#  when: apache_auth.ssl.enabled
#  notify: restart apache

- name: install apache template
  template: src=auth_basic/etc/apache2/sites-available/auth_basic.conf
            dest=/etc/apache2/sites-available/{{ apache_auth.vhost_name }}.conf
  notify: restart apache

- name: basic auth users
  htpasswd: name={{ item.username }} password={{ item.password }}
            path="/etc/apache2/{{ apache_auth.vhost_name }}_passwd"
  with_items: "{{ apache_auth.basic.users }}"
  no_log: true

- name: enable site
  apache2_site: name={{ apache_auth.vhost_name }}.conf
  notify: restart apache

- meta: flush_handlers

- name: ensure apache is running
  service: name=apache2 state=started enabled=yes

#- include: checks.yml
#  when: sensu.client.enable_checks|default('True')|bool
#  tags: sensu-checks

#- include: metrics.yml
#  when: sensu.client.enable_metrics|default('True')|bool
#  tags: sensu-metrics

#- include: serverspec.yml
#  when: serverspec.enabled|default("True")|bool
#  tags: serverspec
