---
- name: copy sensu-client plugins
  copy:
    src: "{{ item }}"
    dest: /opt/sitecontroller/sensu-plugins/
    mode: 0755
  with_fileglob: opt/sitecontroller/sensu-plugins/*
  notify: restart sensu-client

- name: install sensu-server process check
  sensu_process_check: service=sensu-server
  notify: restart sensu-client missing ok

- name: install sensu-api process check
  sensu_process_check: service=sensu-api
  notify: restart sensu-client missing ok

- name: install uchiwa process check
  sensu_process_check: service=uchiwa
  notify: restart sensu-client missing ok

- name: install sensu-api health check
  sensu_check_dict:
    name: check-sensu-api-health
    check: "{{ sensu_checks.sensu_api.check_sensu_api_health }}"

- name: install uchiwa health check
  sensu_check_dict:
    name: check-uchiwa-health
    check: "{{ sensu_checks.uchiwa.check_uchiwa_health }}"
