---
- name: start sensu
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - sensu-api
    - sensu-server

- name: stop sensu
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - sensu-api
    - sensu-server

- name: kill sensu
  shell: "cat /var/run/sensu/sensu*-{{ item }}.pid | xargs -r -I% kill -9 %"
  with_items:
    - api
    - server

- name: restart sensu
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-api # need this up before sensu-server gets restarted
    - sensu-server

- name: restart sensu dashboard
  service:
    name: uchiwa
    state: restarted

- name: restart sensu server
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-server

- name: restart sensu api
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sensu-api
