---
site_abrv: example
stack_name: example
datacenter: example
public_interface: ansible_eth2
private_interface: ansible_eth1
public_ipv4: "{{ hostvars[inventory_hostname][public_interface]['ipv4'] }}"
private_ipv4: "{{ hostvars[inventory_hostname][private_interface]['ipv4'] }}"

serverspec:
  enabled: True

sensu:
  client:
    enable_metrics: false
    enable_checks: true
    rabbitmq:
      host: "{{ hostvars[groups['rabbitmq'][0]][private_interface]['ipv4']['address'] }}"
      username: sensu
      password: sensu
      vhost: /sensu
      hostgroup: sensu

netdata:
  config:
    backend:
      enabled: "yes"
      type: graphite
      destination: "{{ hostvars[groups['graphite'][0]][private_interface]['ipv4']['address'] }}:2003"
      data_source: as collected
      prefix: "{{ monitoring_common.graphite.cluster_prefix }}"
      hostname: "{{ ansible_nodename }}"
      update_every: 10
      buffer_on_failures: 10
      timeout_ms: 20000
      send_charts_matching: "*"
