---
public_interface: ansible_eth1
private_interface: ansible_eth2
public_ipv4: "{{ hostvars[inventory_hostname][public_interface]['ipv4'] }}"
private_ipv4: "{{ hostvars[inventory_hostname][private_interface]['ipv4'] }}"

kibana:
  config:
    elasticsearch_url: "http://{{ hostvars['elk01'][private_interface]['ipv4']['address'] }}:9200"

elasticsearch:
  config:
    cluster.name: "elk_{{ stack_name }}"
    discovery.zen.minimum_master_nodes: "{{ (groups['elasticsearch']|length / 2)|int + (groups['elasticsearch']|length % 2 > 0)|int }}"
    discovery.zen.ping.unicast.hosts: "['{{ hostvars['elk01'][private_interface]['ipv4']['address'] }}','{{ hostvars['elk02'][private_interface]['ipv4']['address'] }}']"
    gateway.expected_nodes: "{{ groups['elasticsearch']|length }}"
    gateway.recover_after_nodes: "{{ (groups['elasticsearch']|length / 2)|int + (groups['elasticsearch']|length % 2 > 0)|int }}"
    cluster.routing.allocation.disk.watermark.low: 5gb
    cluster.routing.allocation.disk.watermark.high: 2gb
    node.name: "{{ ansible_hostname }}"
    node.master: true
    node.data: true
    path.conf: /etc/elasticsearch
    path.data: /var/lib/elasticsearch
    path.logs: /var/log/elasticsearch
    network.host: 0.0.0.0
    http.bind_host: 0.0.0.0
    network.publish_host: "{{ private_ipv4.address }}"
  curator:
    tasks:
      - action: delete
        older: 2
        hour: 2
      - action: close
        older: 2
        hour: 2
        minute: 15
      - action: optimize
        params: "--max_num_segments 1"
        older: 2
        hour: 3
        minute: 0
      - action: bloom
        state: absent
  firewall:
    - port: 9200
      src:
        - "{{ hostvars['elk01'][private_interface]['ipv4']['address'] }}/32"
        - "{{ hostvars['elk02'][private_interface]['ipv4']['address'] }}/32"
        - "{{ hostvars['kibana01'][private_interface]['ipv4']['address'] }}/32"
    - port: 9300
      src:
        - "{{ hostvars['elk01'][private_interface]['ipv4']['address'] }}/32"
        - "{{ hostvars['elk02'][private_interface]['ipv4']['address'] }}/32"
  heap_size: 512m
  restart_on_config: true

logging:
  forward:
    host: "{{ hostvars['elk01'][private_interface]['ipv4']['address'] }}"

apache:
  listen:
    - 80
    - 443
    - 127.0.0.1:8080

control_dashboard:
  http_redirect: False
  apache:
    servername: control.local
  listen:
    ip: "127.0.0.1"
    port: 8080
  locations:
    root:
      path: "/"
    kibana:
      proxy: "http://127.0.0.1:5601/"
      url: "/kibana/"
    elasticsearch:
      proxy: "http://127.0.0.1:5601/"
      url: "/kibana/elasticsearch/"
