---
allow_duplicates: yes
dependencies:
  - role: logging-config
    service: apache
    logdata: "{{ apache.logs }}"
    forward_type: "{{ apache.logging.forwarder }}"
    when: logging.enabled|default("True")|bool
  - role: sensu/check
